export const classes = [
  "Artificer",
  "Barbarian",
  "Bard",
  "Cleric",
  "Druid",
  "Fighter",
  "Monk",
  "Paladin",
  "Ranger",
  "Rogue",
  "Sorcerer",
  "Warlock",
  "Wizard",
];

export const subClasses = {
  artificer: ["Alchemist", "Armorer", "Artillerist", "Battle Smith"],
  barbarian: [
    "Ancestral Guardian",
    "Battlerager",
    "Beast",
    "Berserker",
    "Storm Herald",
    "Totem Warrior",
    "Wild Magic",
    "Zealot",
  ],
  bard: [
    "Creation",
    "Eloquence",
    "Glamour",
    "Lore",
    "Spirits",
    "Swords",
    "Valor",
    "Whispers",
  ],
  cleric: [
    "Arcana",
    "Death",
    "Forge",
    "Grave",
    "Knowledge",
    "Life",
    "Light",
    "Nature",
    "Order",
    "Peace",
    "Tempest",
    "Trickery",
    "Twilight",
    "War",
  ],
  druid: ["Dreams"],
  fighter: ["Arcane Archer"],
  monk: ["Ascendant Dragon"],
  paladin: ["Ancients"],
  ranger: ["Beast Master"],
  rogue: ["Arcane Trickster"],
  sorcerer: ["Aberrant Mind"],
  warlock: ["Archfey"],
  wizard: ["Abjuration"],
};
